### PR TITLE
added 2 event seeds to the app

### PR DESCRIPTION
**Pull request by clydeautin**
## Type of Change
- [x] New Feature
- [ ] Debugging
- [ ] Refactor
- [ ] Documentation

## PR Issue link if applicable
https://concertmate.atlassian.net/browse/KAN-39?atlOrigin=eyJpIjoiOWZlZjg0MTQ2OTI5NGNmNDhlOTdmYThiZjc5Y2VjNzMiLCJwIjoiaiJ9

## Describe Changes Made
I added 2 seed files, small PR but I want to see if this will work on your machines, I had to do a bunch of setup, not sure how much will go up to Github or how much needs to be done on each individual machines

## PR Checklist
- [x] Added Reviewer
- [ ] Followed TDD, And Test are Passing

### CODE REVIEW

**Review by zach-bergman — APPROVED** [review]
A lot of extra files here that we probably don't need to include in our repo, gitignore the environment folder?

**Comment by clydeautin** [comment]
> A lot of extra files here that we probably don't need to include in our repo, gitignore the environment folder?

Yea that could be a good idea going forward, I noticed the file was 26 MB when I uploaded it

**Comment by RodrigoACG** [comment]
> > A lot of extra files here that we probably don't need to include in our repo, gitignore the environment folder?
> 
> Yea that could be a good idea going forward, I noticed the file was 26 MB when I uploaded it

Yeah i was thinking the same thing just to make the app run faster.

**Review by RodrigoACG — APPROVED** [review]

**Comment by GBowman1** [comment]
Screenshot 2024-08-27 at 12 57 51 AM

**Comment by GBowman1** [comment]
need to remove whatever git is tracking for the 1.1 million lines and re push it

**Pull request closed without merging**
